name: Run action
on:
  workflow_dispatch:

jobs:
  case1:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      - uses: ./
        with:
          user: actions-user
      - run: bash .github/workflows/display.bash

  # case2:
  #   strategy:
  #     matrix:
  #       os:
  #         - macos-latest
  #         - ubuntu-latest
  #         - windows-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     # https://github.com/actions/checkout
  #     - uses: actions/checkout@v4
  #       with:
  #         path: myaction
  #     # https://github.com/actions/checkout
  #     - uses: actions/checkout@v4
  #       with:
  #         path: target
  #     - uses: ./myaction/
  #       with:
  #         path: target
  #         user: github-actions
  #     - run: bash ../myaction/.github/workflows/display.bash
  #       working-directory: target

  # case3:
  #   strategy:
  #     matrix:
  #       os:
  #         - macos-latest
  #         - ubuntu-latest
  #         - windows-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     # https://github.com/actions/checkout
  #     - uses: actions/checkout@v4
  #     - uses: ./
  #       with:
  #         global: true
  #         user: latest-commit
  #     - run: bash .github/workflows/display.bash
